---
- name: Create new PostgreSQL user
  hosts: all
  gather_facts: no
  become: false

  vars:
    db_name: "awxdb"
    login_user: "awxuser"
    login_password: "awxpass"
    login_host: "192.168.217.131"
    login_port: 5432

  tasks:
    - name: Validate required vars
      assert:
        that:
          - new_db_user is defined
          - new_db_pass is defined
        fail_msg: "new_db_user and new_db_pass must be supplied (via template variables or survey)."

    - name: Ensure PostgreSQL user exists
      community.postgresql.postgresql_user:
        name: "{{ new_db_user }}"
        password: "{{ new_db_pass }}"
        priv: "{{ db_name }}:ALL"
        state: present
        login_user: "{{ login_user }}"
        login_password: "{{ login_password }}"
        login_host: "{{ login_host }}"
        login_port: "{{ login_port }}"
      no_log: true

    - name: Show user created
      debug:
        msg: "User {{ new_db_user }} created successfully in database {{ db_name }}"
