credentials:
  secretContents:
    cloud: |
      [default]
      aws_access_key_id=minio
      aws_secret_access_key=minio123

configuration:
  backupStorageLocation:
    - name: minio
      bucket: velero
      provider: aws
      config:
        region: minio
        s3ForcePathStyle: true
        s3Url: http://minio.velero.svc:9000

snapshotsEnabled: false

# Fix kubectl image
kubectl:
  image:
    repository: bitnami/kubectl
    tag: "1.32.0"

